# Generated by Django 5.2.6 on 2025-09-25 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('cnh_numero', models.CharField(blank=True, max_length=30, verbose_name='Registro CNH')),
                ('cnh_validade', models.DateField(verbose_name='Validade CNH')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.PositiveBigIntegerField()),
                ('chassi', models.CharField(blank=True, max_length=100, null=True)),
                ('km_atual', models.PositiveIntegerField(default=0)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('disponível', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('km_inicio', models.PositiveIntegerField()),
                ('km_fim', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caucao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='locar.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='locar.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('manutencao', 'Manutenção'), ('multa', 'Multa'), ('seguro', 'Seguro'), ('ipva', 'IPVA'), ('outros', 'Outros')], max_length=50)),
                ('descricao', models.CharField(max_length=400)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/%d/')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='locar.veiculo')),
            ],
        ),
    ]
