# Generated by Django 5.2.6 on 2025-09-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='fipe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='FIPE'),
        ),
    ]
