# Generated by Django 5.2.6 on 2025-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0003_cliente_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='documentos_locacao',
            field=models.FileField(blank=True, default='Sem documento Anexado', null=True, upload_to='', verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnh_numero',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Registro CNH'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnh_validade',
            field=models.DateField(blank=True, verbose_name='Validade CNH'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacao',
            field=models.TextField(blank=True, default='Nenhuma Observação Cadastrada', null=True, verbose_name='Observação'),
        ),
    ]
