# Generated by Django 5.2.6 on 2025-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0004_locacao_documentos_locacao_alter_cliente_cnh_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='foto_veiculo',
            field=models.ImageField(default='Sem foto Adicionado', upload_to='veiculos/'),
        ),
    ]
