# Generated by Django 5.2.6 on 2025-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0005_veiculo_foto_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacao',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto_veiculo',
            field=models.ImageField(blank=True, upload_to='veiculos/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('disponível', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo')], default='disponível', max_length=20),
        ),
    ]
