# Generated by Django 5.2.6 on 2025-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0006_alter_locacao_options_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em Andamento'), ('encerrada', 'Encerrada')], default='ativa', max_length=10),
        ),
    ]
