# Generated by Django 5.2.6 on 2025-09-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0007_locacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('avista', 'À Vista'), ('semanal', 'Semanal')], default='avista', max_length=10),
        ),
    ]
