# Generated by Django 5.2.6 on 2025-09-30 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0008_locacao_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='locar.locacao')),
            ],
        ),
    ]
