# Generated by Django 5.2.6 on 2025-10-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0009_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='valor_diaria',
        ),
    ]
