# Generated by Django 5.2.6 on 2025-10-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0010_remove_veiculo_valor_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='renavan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RENAVAN'),
        ),
    ]
