# Generated by Django 5.2.6 on 2025-10-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0011_veiculo_renavan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='renavan',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RENAVAm'),
        ),
    ]
