# Generated by Django 5.2.6 on 2025-10-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0012_remove_veiculo_renavan_veiculo_renavam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='pago',
        ),
        migrations.AlterField(
            model_name='locacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('avista', 'À Vista'), ('semanal', 'Semanal')], default='semanal', max_length=10),
        ),
    ]
