# Generated by Django 5.2.6 on 2025-10-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0013_remove_locacao_pago_alter_locacao_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(blank=True, choices=[('andamento', 'Em Andamento'), ('encerrada', 'Encerrada')], default='andamento', max_length=10, null='True'),
        ),
    ]
