# Generated by Django 5.2.6 on 2025-10-10 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0014_cliente_ativo_alter_locacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='locar.veiculo'),
        ),
    ]
