# Generated by Django 5.2.6 on 2025-10-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0015_alter_locacao_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ativo',
        ),
    ]
