# Generated by Django 5.2.6 on 2025-10-12 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0016_remove_cliente_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_prevista', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='locar.locacao')),
            ],
            options={
                'ordering': ['data_prevista'],
            },
        ),
    ]
