# Generated by Django 5.2.6 on 2025-10-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0017_parcela'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcela',
        ),
    ]
