# Generated by Django 5.2.6 on 2025-10-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0018_delete_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='semanas_pagas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
