# Generated by Django 5.2.6 on 2025-10-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0019_locacao_semanas_pagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='quantidade_semanas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='semanas_pagas',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
