# Generated by Django 5.2.6 on 2025-10-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0020_locacao_quantidade_semanas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='quantidade_semanas',
            field=models.IntegerField(default=0),
        ),
    ]
