# Generated by Django 5.2.6 on 2025-10-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0021_alter_locacao_quantidade_semanas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locacao',
            old_name='valor_total',
            new_name='valor_semanal',
        ),
    ]
