# Generated by Django 5.2.6 on 2025-11-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0022_rename_valor_total_locacao_valor_semanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnh_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade CNH'),
        ),
    ]
