# Generated by Django 5.2.6 on 2025-11-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0023_alter_cliente_cnh_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='caucao_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('devolvido', 'Devolvido'), ('retido', 'Retido')], default='pendente', max_length=20, verbose_name='Status do Caução'),
        ),
    ]
