# Generated by Django 5.2.6 on 2025-11-10 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0024_locacao_caucao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='caucao_status',
        ),
    ]
