# Generated by Django 5.2.6 on 2025-11-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0025_remove_locacao_caucao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='inicio',
            field=models.DateField(),
        ),
    ]
