# Generated by Django 5.2.6 on 2025-11-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0026_alter_locacao_fim_alter_locacao_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='inicio',
            field=models.DateTimeField(),
        ),
    ]
