# Generated by Django 5.2.6 on 2025-11-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0027_alter_locacao_fim_alter_locacao_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='caucao_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('devolvido', 'Devolvido'), ('retido', 'Retido')], default='pendente', max_length=20),
        ),
    ]
