# Generated by Django 5.2.6 on 2025-11-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0028_locacao_caucao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='caucao_status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('devolvido', 'Devolvido'), ('retido', 'Retido')], default='pendente', max_length=20, null=True),
        ),
    ]
