# Generated by Django 5.2.6 on 2025-11-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0029_alter_locacao_caucao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento_com_foto',
            field=models.FileField(blank=True, default='Sem documento Anexado', null=True, upload_to='', verbose_name='CNH'),
        ),
    ]
