# Generated by Django 5.2.6 on 2025-11-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0030_cliente_documento_com_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento_com_foto',
            field=models.FileField(blank=True, default='Sem documento Anexado', null=True, upload_to='documentos/clientes/', verbose_name='CNH'),
        ),
    ]
