# Generated by Django 5.2.6 on 2025-11-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0031_alter_cliente_documento_com_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='documento_veiculo',
            field=models.FileField(blank=True, default='Sem documento Anexado', null=True, upload_to='documentos-veiculos/', verbose_name='CRVL-Digital'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_com_foto',
            field=models.FileField(blank=True, default='Sem documento Anexado', null=True, upload_to='documentos-clientes/', verbose_name='CNH'),
        ),
    ]
