# Generated by Django 5.2.6 on 2025-11-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0032_veiculo_documento_veiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento_com_foto',
            field=models.FileField(blank=True, null=True, upload_to='documentos-clientes/', verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RENAVAM'),
        ),
    ]
