# Generated by Django 5.2.6 on 2025-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0033_alter_cliente_documento_com_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='documento_veiculo',
            field=models.FileField(blank=True, null=True, upload_to='documentos-veiculos/', verbose_name='CRVL-Digital'),
        ),
    ]
