# Generated by Django 5.2.6 on 2025-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0034_alter_veiculo_documento_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento_com_foto',
            field=models.FileField(blank=True, null=True, upload_to='documentos-clientes/', verbose_name='Documento com Foto'),
        ),
    ]
