# Generated by Django 5.2.6 on 2025-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locar', '0035_alter_cliente_documento_com_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='documentos_locacao',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Documentos'),
        ),
    ]
